### ISSUE TITLE
Encontrar proyecto en sicoes

### ISSUE THREAD

**Issue by hrnn** [PixiesUPB/PixiesUPB#1]
## Historia de Usuario 

Como equipo quiero obtener una idea de proyecto en sicoes

## Criterio de Aceptación 

- [x] Subir idea de proyecto en plataforma virtual

**Comment by hrnn** [comment]
Encontre la pagina de sicoes es  https://www.sicoes.gob.bo/

**Comment by MateoAltamirano** [comment]
Encontramos esta opción de proyecto
https://www.sicoes.info/convocatoria/implementacion-de-un-sistema-academico-integrado-para-carrera-de-derecho-1
