### ISSUE TITLE
Elegir el Bootstrap que usaremos 

### ISSUE THREAD

**Issue by Emmilili** [PixiesUPB/PixiesUPB#12]
## Historias de Usuario
Como equipo queremos escoger un bootstrap que sea adecuado a los requerimientos del documento de SICOES para una trabajo exitoso. 

## Criterio de aceptación
- [x]  Elegir el bootstrap

**Comment by MateoAltamirano** [comment]
https://themewagon.com/themes/free-bootstrap-4-html5-education-website-template-academics/
