### ISSUE TITLE
Realizar la documentación para la primera parte del proyecto 

### ISSUE THREAD

**Issue by Emmilili** [PixiesUPB/PixiesUPB#13]
## Historia de Usuario
Como equipo queremos tener una buena documentación del proyecto para poder lograr los objetivos esperados por el docente

## Criterio de Aceptación
- [x] Descripción del proyecto 
- [x] Casos de Uso 
- [x] Mockups
- [x] Arquitectura de Software 
- [x] Scrum

**Comment by MateoAltamirano** [comment]
Introduccion añadida

**Comment by WeimarAlexanderTorresHerrera** [comment]
Arquitectura de Software añadida

**Comment by WeimarAlexanderTorresHerrera** [comment]
Inicio de documentación de Sprint 1

**Comment by MateoAltamirano** [comment]
Casos de uso añadidos

**Comment by WeimarAlexanderTorresHerrera** [comment]
Actualización de Sprint 1

**Comment by Emmilili** [comment]
Añadiendo Mockups más el Link del flujo de pantallas

**Comment by MateoAltamirano** [comment]
completado
