### ISSUE TITLE
Definir que herramienta se usará para los diagramas

### ISSUE THREAD

**Issue by WeimarAlexanderTorresHerrera** [PixiesUPB/PixiesUPB#18]
## Historia de Usuario
Como equipo se quiere definir una herramienta para poder realizar los diagramas

## Criterios de Aceptación
- [x]  Definir herramienta

**Comment by WeimarAlexanderTorresHerrera** [comment]
@MateoAltamirano Que herramienta usaremos para los casos de uso?
Conozco Lucidchart [https://www.lucidchart.com/](url) y tambien Visual

**Comment by MateoAltamirano** [comment]
@WeimarAlexanderTorresHerrera yo creo que todo con draw.io
