### ISSUE TITLE
Realizar documentacion del scrum - Sprint 1

### ISSUE THREAD

**Issue by WeimarAlexanderTorresHerrera** [PixiesUPB/PixiesUPB#19]
## Historia de Usuario
Como equipo queremos realizar una documentación del proceso de scrum para reconocer fácilmente que tareas se realizaron.
## Criterio de Aceptación
- [x]  Documentar sprint 1

**Comment by WeimarAlexanderTorresHerrera** [comment]
La documentación de las tareas realizadas hasta este momento esta añadida

**Comment by MateoAltamirano** [comment]
Casos de uso, diagramas de casos de uso y eleccion de bootstrap añadidos
