### ISSUE TITLE
Detallar los usuarios en la Wiki

### ISSUE THREAD

**Issue by MateoAltamirano** [PixiesUPB/PixiesUPB#25]
## Historia de Usuario
Como equipo queremos detellar los usuarios que identificamos en la wiki para entender mejor el rol que cumplen en el sistema

## Criterio de Aceptacion
- [x] Detallar usuarios

**Comment by MateoAltamirano** [comment]
Ya detalle los usuarios

**Comment by Emmilili** [comment]
Como funciona el kardex?

**Comment by MateoAltamirano** [comment]
Se encargara de algunos procesos académicos y tener la información centralizada.
