### ISSUE TITLE
Crear el proyecto inicial (código)

### ISSUE THREAD

**Issue by MateoAltamirano** [PixiesUPB/PixiesUPB#28]
## Historia de Usuario
Como equipo queremos crear el proyecto inicial para empezar a realizar el código.

## Criterion de Aceptación
- [x] Subir el proyecto inicial al repositorio

**Comment by Emmilili** [comment]
Haremos sólo la parte de Front-end? o Back-end también?

**Comment by MateoAltamirano** [comment]
Los 2 en el repositorio

**Comment by MateoAltamirano** [comment]
ya hice el primer commit
