### ISSUE TITLE
Diseñar la arquitectura del proyecto

### ISSUE THREAD

**Issue by MateoAltamirano** [PixiesUPB/PixiesUPB#3]
## Historia de Usuario 
Como equipo queremos diseñar la arquitectura del proyecto para tener clara la estructura al momento del desarrollo

## Criterio de Aceptación
- [x] Diseños en diagramas
- [x] Definir base de datos

**Comment by WeimarAlexanderTorresHerrera** [comment]
@hrnn En el documento nos dan una arquitectura para el proyecto, esta es valida como un diagrama de arquitectura?

![Arquitectura](https://user-images.githubusercontent.com/37818293/69424947-41018080-0d00-11ea-8a03-79bd54635029.jpg)

**Comment by hrnn** [comment]
@WeimarAlexanderTorresHerrera Es valida pero no para su proyecto, en su caso tal vez solo requieran 2 servidores en vez de 5, uno para servicios y el otro para la base de datos.
Ahora si lo veo valido para el caso de una arquitectura de microservicios, ya que tendrían 3 microservicios y una base de datos.

**Comment by WeimarAlexanderTorresHerrera** [comment]
@hrnn Puede verificar si el diseño de este diagrama es correcto
![Arquitectura de Software](https://user-images.githubusercontent.com/37818293/69472956-f5de8080-0d86-11ea-8e4a-92bf806c0c6b.jpg)

**Comment by WeimarAlexanderTorresHerrera** [comment]
@hrnn Y nos puede ayudar a definir que servicios se tendrían con los requerimientos que tenemos... [https://github.com/PixiesUPB/PixiesUPB/wiki/1.-Descripci%C3%B3n-del-proyecto](url) (Aquí están los requerimientos).

**Comment by WeimarAlexanderTorresHerrera** [comment]
Diagramas de arquitectura, frontend y backend terminadas
