### ISSUE TITLE
Definir que herramientas se usaran para hacer Swagger Documentation

### ISSUE THREAD

**Issue by WeimarAlexanderTorresHerrera** [PixiesUPB/PixiesUPB#49]
## Historia de Usuario
Como equipo queremos definir que herramientas se usaran para realizar la documentación en Swaggger
## Criterios de Aceptación
- [x]  Definir herramientas

**Comment by WeimarAlexanderTorresHerrera** [comment]
Se usaran librerías ya definidas como:
- swagger-ui-express
- swagger.docs
- swagger viewer

**Comment by MateoAltamirano** [comment]
Super
