### ISSUE TITLE
Definir los usuarios del proyecto

### ISSUE THREAD

**Issue by MateoAltamirano** [PixiesUPB/PixiesUPB#5]
## Historia de Usuario
Como equipo queremos definir los usuarios que utilizarán el proyecto para implementar su funcionalidad

## Criterio de Aceptación
- [ ] Definir usuarios

**Comment by WeimarAlexanderTorresHerrera** [comment]
Se busca la información y/o funcionalidad que no piden en los documentos del proyecto para determinar cuales son los usuarios requeridos.

**Comment by WeimarAlexanderTorresHerrera** [comment]
Se encontró que se tienen principalmente 3 usuarios, Estudiantes, Docentes y Kardex. Puede que existan mas usuarios requeridos.

**Comment by WeimarAlexanderTorresHerrera** [comment]
Como grupo determinamos que nos quedemos con solo los 3 usuarios requeridos ya que incluir uno mas podría aumentar el tiempo de realización del proyecto.
