### ISSUE TITLE
Crear el diagrama orientado a objetos

### ISSUE THREAD

**Issue by Emmilili** [PixiesUPB/PixiesUPB#59]
### Historia de Usuario 
Como equipo queremos realizar el diagrama orientado a objetos de nuestro proyecto para tener una buena documentación. 

### Criterios de Aceptación
- [x] Añadir el diagrama orientado a objetos a la wiki

**Comment by MateoAltamirano** [comment]
Ya esta el diagrama, mañana le mostrare al Hernan
