### ISSUE TITLE
Añadir GET estudiante a swagger

### ISSUE THREAD

**Issue by WeimarAlexanderTorresHerrera** [PixiesUPB/PixiesUPB#64]
## Historia de Usuario
Como equipo queremos añadir a swagger el api GET estudiante
## Criterios de Aceptación
- [x] GET estudiante individual añadido
- [x] GET estudiantes añadido

**Comment by WeimarAlexanderTorresHerrera** [comment]
GET estudiante añadido

**Comment by WeimarAlexanderTorresHerrera** [comment]
GET todos lo estudiantes añadido

**Comment by MateoAltamirano** [comment]
Hay que ver si usaremos {id} o :id
