### ISSUE TITLE
Añadir POST estudiante a swagger

### ISSUE THREAD

**Issue by WeimarAlexanderTorresHerrera** [PixiesUPB/PixiesUPB#65]
## Historia de Usuario
Como equipo queremos añadir a swagger el api POST estudiante
## Criterios de Aceptación
- [x] POST añadido

**Comment by WeimarAlexanderTorresHerrera** [comment]
POST añadido

**Comment by MateoAltamirano** [comment]
Usa los datos que le pasan en body asi que esta bien
