### ISSUE TITLE
Añadir PUT estudiantes a swagger

### ISSUE THREAD

**Issue by WeimarAlexanderTorresHerrera** [PixiesUPB/PixiesUPB#66]
## Historia de Usuario
Como equipo queremos añadir a swagger el api PUT estudiante para poder tener mas documentado nuestra api
## Criterios de Aceptación
- [x] PUT añadido

**Comment by WeimarAlexanderTorresHerrera** [comment]
PUT estudiantes añadido

**Comment by MateoAltamirano** [comment]
Funciona
