### ISSUE TITLE
Añadir DELETE estudiante a swagger

### ISSUE THREAD

**Issue by WeimarAlexanderTorresHerrera** [PixiesUPB/PixiesUPB#67]
## Historia de Usuario
Como equipo queremos añadir a swagger el api DELETE estudiante para poder tener mas documentado nuestra api
## Criterios de Aceptación
- [x] DELETE añadido

**Comment by MateoAltamirano** [comment]
Creo que ya esta el pull request revisado

**Comment by MateoAltamirano** [comment]
Ya esta todo el api
