### ISSUE TITLE
Definir la herramienta para realizar mockups

### ISSUE THREAD

**Issue by WeimarAlexanderTorresHerrera** [PixiesUPB/PixiesUPB#7]
## Historia de Usuario
Como equipo queremos determinar la herramienta mas eficaz para realizar los mockups

## Criterio de Aceptación
- [x] Definir una herramienta

**Comment by Emmilili** [comment]
MarvelApp es la aplicación que usaremos para los mocks. Debido a haberlo visto anteriormente y que todo el equipo se encuentra familiarizado.
