### ISSUE TITLE
Definir las tecnologias a usar en front-end

### ISSUE THREAD

**Issue by hrnn** [PixiesUPB/PixiesUPB#8]
## Historia de Usuario
Como equipo queremos definir las tenologias que usaremos en front-end para poder implmentar el proyecto

## Criterio de Aceptación
- [x] Seleccionar tecnologia

**Comment by MateoAltamirano** [comment]
@Emmilili  tu tienes mas experiencia en web, que crees que usaremos?

**Comment by Emmilili** [comment]
> @Emmilili tu tienes mas experiencia en web, que crees que usaremos?

Lo mejor sería para ahorrar tiempo Bootstrap :)
