### ISSUE TITLE
Definir tecnologias a usar en back-end 

### ISSUE THREAD

**Issue by hrnn** [PixiesUPB/PixiesUPB#9]
## Historia de Usuario
Como equipo queremos definir las tenologias que usaremos en back-end para poder implementar el proyecto

## Criterio de Aceptación
- [x] Seleccionar tecnologia

**Comment by WeimarAlexanderTorresHerrera** [comment]
Se intenta definir entre los lenguajes PHP y Javascript

**Comment by WeimarAlexanderTorresHerrera** [comment]
@MateoAltamirano @Emmilili Cual es su conocimiento en estos lenguajes? (Bajo, Medio, Alto): 
Weimar -> PHP Bajo
                   Javascript Bajo

**Comment by MateoAltamirano** [comment]
Medio en ambos

**Comment by Emmilili** [comment]
Medio en ambos también

**Comment by WeimarAlexanderTorresHerrera** [comment]
La tecnología a usar sera Javascript ya que nos sera de utilidad mejorar nuestros conocimientos en este lenguaje
